<?php
/**
 * @file
 * Code for the social_media_links feature.
 */

include_once 'social_media_links.features.inc';

$module_path = drupal_get_path('module', 'social_media_links');
drupal_add_js($module_path . '/js/list.js');
drupal_add_js($module_path . '/js/social_media_links_pane.js');

/**
 * Implements hook_ctools_plugin_directory().
 */
function social_media_links_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}
